name: Daily GitHub Green Dot

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  daily-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Update README daily section
        run: |
          DATE=$(date '+%Y-%m-%d')
          if grep -q "<!--START_SECTION:DAILY-->" README.md; then
            sed -i "/<!--START_SECTION:DAILY-->.*<!--END_SECTION:DAILY-->/c\<img src=\"https://readme-typing-svg.demolab.com?font=Exo+2&weight=500&size=24&pause=1000&color=36BCF7,FF6EC7&background=FFFFFF00&width=500&lines=Last+update:+$DATE\" alt=\"Daily Update\"/>" README.md
          else
            echo -e "\n<!--START_SECTION:DAILY-->\n<img src=\"https://readme-typing-svg.demolab.com?font=Exo+2&weight=500&size=24&pause=1000&color=36BCF7,FF6EC7&background=FFFFFF00&width=500&lines=Last+update:+$DATE\" alt=\"Daily Update\"/>" >> README.md
          fi

      - name: Configure Git
        run: |
          git config user.name "AbsoluteZero"
          git config user.email "186853152+AbsoluteZero001@users.noreply.github.com"

      - name: Commit and push changes
        run: |
          git add README.md
          git commit -m "Daily progress update: $DATE" || echo "No changes to commit"
          git push
